### PR TITLE
Test Time#yday for each day of each month

### PR DESCRIPTION
**Pull request by elia**

### CODE REVIEW

**Comment by elia** [comment]
Maybe I should also mention that the code comes from this comment by @wmnnd:

https://github.com/opal/opal/pull/636#issuecomment-60464007

**Comment by eregon** [comment]
I rebased the commit on top of current master.

**Comment by eregon** [comment]
@elia I included the link in the commit and fixed a bit the style, does it look alright for you?

**Comment by eregon** [comment]
Merged, thanks @elia and @wmnnd!

**Comment by elia** [comment]
Thanks!

**Pull request merged**
