### PR TITLE
updated latest patch version for ruby-2.1 and 2.0

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by eregon** [comment]
2.1.6 is not available on OS X yet (see the builder).
The patchlevel on 2.0.0 also guarantees us a minimum version, what is the advantage of removing it?

**Comment by ferdinandrosario** [comment]
ok. Removing specific patch version will ensure that travis alway check against the latest patch...

**Comment by eregon** [comment]
Right, I remember adding the patch number to force OS X builder to use sth recent enough.
So I guess we'll need to wait a bit more before doing this update.

**Comment by ferdinandrosario** [comment]
:+1:

**Comment by eregon** [comment]
Fixed!

**Comment by ferdinandrosario** [comment]
:+1:

**Pull request closed without merging**
