### PR TITLE
removed net-telnet specs

### PR DESCRIPTION
**Pull request by hsbt**
I removed net-telnet from stdlib at https://github.com/ruby/ruby/commit/0b5ecba435280947a16ab08fac0592fb3dc915d2

### CODE REVIEW

**Comment by eregon** [comment]
Looks good :+1: (will merge when the second CI passes)

**Comment by eregon** [comment]
Merged, thanks!

**Comment by hsbt** [comment]
:+1:

**Comment by headius** [comment]
Is net/telnet now available externally as a gem? If so, perhaps the specs
should be transplanted there?

**Comment by hsbt** [comment]
@headius I wiil export this specs to ruby/net-telnet.

**Pull request merged**
