### PR TITLE
Test creating classes within Class.new blocks

### PR DESCRIPTION
**Pull request by wied03**
Something Opal might be having problems with, couldn't find an existing rubyspec for this

### CODE REVIEW

**Comment by eregon** [comment]
This is actually just exhibiting how the constant namespace works.
Anonymous class bodies, like any other blocks are just ignored.
Only `module` and `class` can change the lexical scope used for constant resolution.

**Comment by eregon** [comment]
So this somehow duplicates specs in https://github.com/ruby/rubyspec/blob/master/language/constants_spec.rb. These are however complex and would need some refreshment for clarity and to explain the rules better.

**Comment by wied03** [comment]
@eregon - Makes sense. Should this PR be closed then?

**Comment by eregon** [comment]
@wied03 Yes, since the location for the specs is incorrect.
However, could you try to move these new specs to `language/class_spec.rb`, since this is mainly about class definition in blocks?
Some examples in this PR seem really good to illustrate that!

**Pull request closed without merging**
