### PR TITLE
Make travis bundler version same as Gemfile.lock

### PR DESCRIPTION
**Pull request by JuanitoFatas**

### CODE REVIEW

**Comment by eregon** [comment]
The Travis build does not use Bundler, because it's significantly faster without (1min 50s vs 3min 25s) and it involves less external variables.
Readme instructions have already been updated to not use bundler anymore.

**Comment by JuanitoFatas** [comment]
OK.

**Comment by eregon** [comment]
I am curious, why did you want to update Bundler on Travis for?

**Comment by JuanitoFatas** [comment]
1. Promote bundler v1.10.4 when people see it in `.travis.yml`
2. Same version matched with version we use for development specified in Gemfile.lock
  so when there is a bundler bug found on travis can be sure is caused by bundler `v1.10.4`
3. The `bundle gem` command now recommend this setting in generated `.travis.yml`
4. `v1.10.4` fixed a bug for display native extension output

**Comment by eregon** [comment]
Thanks for the details :)
Well, I don't want to promote Bundler for rubyspec anymore so that's one thing :)
I'd like to remove the Gemfile & lock but maybe wait a bit for the change to happen.
And anyway we used Bundler only to download mspec (that's jsut a `git clone`) and keep it up-to-date (a bit trickier now) so anything more evolved is not needed.

**Comment by JuanitoFatas** [comment]
Ok. In the future let's figure out how to move off the bundler. Cheers.

**Pull request closed without merging**
