### PR TITLE
[language/string] Add specs for String#[]

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Add specs for [String#[]](http://ruby-doc.org/core-2.2.2/String.html#method-i-5B-5D)

```
$ bundle exec mspec -t /Users/Juan/rubies/bin/ruby language/string_spec.rb
String#[]
- returns substring by index
- returns substring by index (backward)
- returns substring by start and length
- returns empty string if start is at end of string
- returns nil if start is out of string
- returns substring by range
- returns substring by regexp
- returns substring by regexp and capture
- returns substring by match string
- returns nil if not found match string
```

### CODE REVIEW

**Comment by vais** [comment]
@JuanitoFatas pardon my ignorance, but my understanding was this should be covered in https://github.com/ruby/rubyspec/blob/master/core/string/element_reference_spec.rb, no?

**Comment by JuanitoFatas** [comment]
@vais Thanks for the heads up.

**Comment by vais** [comment]
@JuanitoFatas no problem, I only know because I had to pass those specs for Opal :smile: The name "element_reference_spec" is a little unfortunate, but calling it the square-bracket-thingy-spec probably would be as confusing :wink:. So, element_reference_spec it is.

**Comment by eregon** [comment]
@vais Thanks for the review :smiley: 

`language` essentially describes the syntax and what is not defined by a method,
`core` specifies methods of classes loaded without any require,
`library` for those which need to require a standard library,
`optional/capi` for the C extensions
and `command_line` for the command line options.

**Comment by vais** [comment]
@eregon makes sense! That's basically my understanding. The joke was that some methods, e.g. `String#[]` are difficult to name using words, and so a name like `element_reference_spec` was chosen kind of arbitrarily and it may not be apparent what it's referring to until you open the file and see. But for lack of a better name, that one will have to do. :beers:

**Pull request closed without merging**
