### PR TITLE
Marshal#dump of Time with a zone changed from 2.1 to 2.2

### PR DESCRIPTION
**Pull request by anthonycrumley**

### CODE REVIEW

**Comment by anthonycrumley** [comment]
@eregon With these commits trunk is running without failures for me.  All the other 2.x versions have some failures when I run them right now.

**Comment by eregon** [comment]
Awesome, I did a couple additional commits and all versions from 2.0 are passing now!

**Comment by hsbt** [comment]
:+1:

**Comment by anthonycrumley** [comment]
:clap:

**Pull request merged**
