### PR TITLE
Fixes for rubyspec archive

### PR DESCRIPTION
**Pull request by eregon**
@hsbt This is a pull request to check Travis status and to coordinates efforts to add the necessary fixes to rubyspec archive branch and then merge with our rubyspec branch (currently named ruby).
Merging from 2 passing branches seems safer than trying to merge a partially problematic one.

I am starting from @anthonycrumley's work.

### CODE REVIEW

**Comment by eregon** [comment]
I'll start by merging mspec first.

**Comment by eregon** [comment]
I changed my strategy to merge rubyspec/archive in ruby/ruby and add fixes on top of the merge.

**Comment by eregon** [comment]
@hsbt @anthonycrumley I managed to [merge](https://github.com/ruby/rubyspec/commits/merge-rubyspec-archive) (in ~6 hours) rubyspec archive branch into ruby/ruby locally and pushed the result to https://github.com/ruby/rubyspec/tree/merge-rubyspec-archive.
Only 14 failures are left on trunk.
I need to update our mspec too so it can actually run them (for the moment I just merged both mspec locally + 2 tiny patches).

@anthonycrumley Thank you for your commits, I could just cherry-pick them to solve half the issues :)
Some were already in the ruby branch, in which case I still merged your additional specs if any.

9 issues are due to Marshal changes, if one of you want to investigate, it looks relatively straightforward.
I will fix the other ones (the String ones are a bit strange, they look like unintended side-effects corrupting some stuff).

**Comment by eregon** [comment]
The mspec I use is in https://github.com/ruby/mspec/tree/both, but it needs clean-up.

**Comment by anthonycrumley** [comment]
@eregon Wow!! Thanks for tackling that beast of a merge.  I will begin looking into the Marshal issues.

**Pull request closed without merging**
