### PR TITLE
Merge rubyspec archive

### PR DESCRIPTION
**Pull request by eregon**
PR to test the build on Travis (try 2).
All ruby between 2.0 and trunk pass locally by running mspec without arguments.

### CODE REVIEW

**Comment by eregon** [comment]
The build is passing, except a couple errors on the "ruby-head" because it more than one week old.
I opened https://github.com/travis-ci/travis-ci/issues/3274 to ask when they will update it.
After that I'll push to master and later delete the `ruby` branch if that is fine?

**Comment by hsbt** [comment]
@eregon Great work! I will confirm this branch on 2.0.0, 2.1, 2.2, trunk.

**Comment by eregon** [comment]
ruby-head was updated, now Travis passes, I'll push to master and remove this branch.
@hsbt Tell me when I can push to the `ruby` branch (if needed at all) and when I can delete it.

**Comment by hsbt** [comment]
@eregon I changed default branch to master from ruby. Please wait to delete ruby branch before confirming to fine on rubyci.org.

**Comment by eregon** [comment]
OK, thanks!

**Comment by eregon** [comment]
Now, `ruby` is the same as `master`, let's wait for RubyCI.

**Pull request closed without merging**
